# Generated by Django 5.2.7 on 2025-10-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('salary_per_day', models.DecimalField(decimal_places=2, help_text='Daily salary in INR', max_digits=10)),
                ('date_joined', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
